# 1. Create a null vector of size 10 but the fifth value which is 1

In [7]:
import numpy as np

null_vector = np.zeros(10)

null_vector[4] = 1

print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 2. Create a vector with values ranging from 10 to 49

In [8]:
import numpy as np

vector = np.arange(10, 50)

print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 3. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
import numpy as np
matrix = np.arange(9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [10]:
import numpy as np
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
print(non_zero_indices)


(array([0, 1, 4], dtype=int64),)


# 5. Create a 10x10 array with random values and find the minimum and maximum values

In [11]:
import numpy as np
random_array = np.random.rand(10, 10)
minimum_value = random_array.min()
maximum_value = random_array.max()
print(random_array)
print(f"Minimum Value: {minimum_value}")
print(f"Maximum Value: {maximum_value}")


[[0.58573728 0.5662594  0.56256799 0.9974574  0.86136941 0.93454398
  0.13796654 0.24523874 0.03401611 0.72585025]
 [0.20522451 0.40716265 0.04258162 0.38053212 0.89338383 0.03977737
  0.7791857  0.45855821 0.08341322 0.67858886]
 [0.85523688 0.0214864  0.84090012 0.3060876  0.55810141 0.82741398
  0.37330288 0.46870882 0.88448128 0.14181469]
 [0.6837951  0.26118652 0.08859925 0.37732495 0.16707869 0.24653013
  0.06215386 0.81647308 0.46201469 0.90495243]
 [0.59432863 0.57554519 0.26415956 0.79234412 0.70294498 0.39021729
  0.50667537 0.01926167 0.39332983 0.60899871]
 [0.56775025 0.94439334 0.5627787  0.48474425 0.33922273 0.73218952
  0.41113827 0.29113621 0.11019433 0.8064163 ]
 [0.83064802 0.78983138 0.61564625 0.24381584 0.76912789 0.35467889
  0.51402068 0.66118549 0.30323153 0.54342139]
 [0.35155133 0.13734707 0.82855063 0.51709024 0.68003828 0.04618097
  0.9882645  0.4704714  0.01341238 0.62885605]
 [0.23608474 0.27504817 0.94817635 0.88310926 0.07008969 0.62070534
  0.33389715

# 6.Create a random vector of size 30 and find the mean value.

In [12]:
import numpy as np
random_vector = np.random.rand(30)
mean_value = random_vector.mean()
print(random_vector)
print(f"Mean Value: {mean_value}")


[0.7821163  0.57631443 0.50922105 0.6693967  0.61848724 0.59218252
 0.54362337 0.93691433 0.21095327 0.48458873 0.20796008 0.47355915
 0.21731556 0.54697797 0.22512623 0.48590666 0.0856131  0.89719415
 0.28305395 0.64197722 0.03689687 0.57901102 0.56438638 0.51846405
 0.202131   0.3948687  0.75370593 0.58256544 0.80545229 0.09970236]
Mean Value: 0.48418886768124986
